
/* Access image by id and change
            the display property to block*/
       
 
          

function show() {
 
	/* Get image and change value
	of src attribute */
            /* Access image by id and change
            the display property to block*/
            document.getElementById('image')
                    .style.display = "block";
}

// Array with all our images
var allImages = [
        "https://d2w9rnfcy7mm78.cloudfront.net/6812977/original_31b5ecf8c94ab5ca04588fe24d15cb48.png?1586591262?bc=0",
        "https://d2w9rnfcy7mm78.cloudfront.net/15916131/original_37ceca008bfbd4a8f1f67a4b65767624.png?1649130720?bc=0",
        "https://d2w9rnfcy7mm78.cloudfront.net/15423102/original_de2bc8c3e9404ca58c21da1812c0943e.png?1646328644?bc=0",
        "https://d2w9rnfcy7mm78.cloudfront.net/4408680/original_aaf2e6c0a5f8e9805b951bfaa7b9b16d.png?1559705096?bc=1",
        "https://d2w9rnfcy7mm78.cloudfront.net/690479/original_e37563ca0c33f1026387585ec7b78dd7.png?1472267219?bc=1",
        "https://d2w9rnfcy7mm78.cloudfront.net/684432/original_959a5f2ef2b6c08272fe123837ee3928.png?1471888832?bc=1",
        "https://d2w9rnfcy7mm78.cloudfront.net/251093/original_b761601dee47dbabb885b6c172ce74cd.png?1404664598?bc=1",
        "https://d2w9rnfcy7mm78.cloudfront.net/769348/original_83d0006f7cc0ad49bd90aa1a001ad67e.png?1479256399?bc=1",
        "https://d2w9rnfcy7mm78.cloudfront.net/1101481/original_76ba39c12004373b2d27691c036b99c2.png?1498681068?bc=1",
        "https://d2w9rnfcy7mm78.cloudfront.net/1772749/original_48e37e88f5132e160cc7d1e2749e069e.png?1518812064?bc=1",
        "https://d2w9rnfcy7mm78.cloudfront.net/2117022/original_9aacf13bb556cd5843b4a5185f92fbdc.png?1525137914?bc=1",
        "https://d2w9rnfcy7mm78.cloudfront.net/3808037/original_77c1714a7ebf72480792940c5fda58a6.png?1551922040?bc=1",
        "https://d2w9rnfcy7mm78.cloudfront.net/5101126/original_4fc1f9778db38cb389ef255b922778a3.png?1569425582?bc=0",
        "https://d2w9rnfcy7mm78.cloudfront.net/5213542/original_2774ba89d8426f5b9dcf8bb0e0489446.png?1570664686?bc=0",
        "https://d2w9rnfcy7mm78.cloudfront.net/7664162/original_c899a61b688a9dc9c5f0c399a862e408.png?1592149941?bc=0",
        "https://d2w9rnfcy7mm78.cloudfront.net/8335066/original_444e697ebf491062b2cbd44d8975fd7d.png?1597420099?bc=0",
      ];
      // The counter
      var count = 0;
      // Wait for the DOM to be loaded
      document.addEventListener("DOMContentLoaded", function () {
        // Select the container
        var container = document.querySelector(".container");
        // Generate a random number
        var randomNumber = function () {
          return Math.floor(Math.random() * allImages.length);
          
        };
        // Place the image generated by loadImage function
        var placeImage = function (x, y, newImage) {
          // Wait for the image to be loaded
          newImage.addEventListener("load", function () {
            // Put the new image into the DOM
            container.append(newImage);
            // Select the new image by his id attribute
            var theImage = document.querySelector('[id="' + count + '"]');
            // Center the image on mouse pointer
            theImage.style.left = x - theImage.width / 2 + "px";
            theImage.style.top = y - theImage.height / 2 + "px";
            // Increment the counter
            count++;
          });
        };
        // Create a new image
        var loadImage = function (x, y) {
          var newImage = new Image();
          // Set the source
          newImage.src = allImages[randomNumber()];
          // Set the attribute Id
          newImage.setAttribute("id", count);
          // Place it
          placeImage(x, y, newImage);
        };
        // Listen to the mouseup event
        document.addEventListener(
          "click",
          function (event) {
            // Get the mouse position
            var x = event.clientX;
            var y = event.clientY;
            // load image
            loadImage(x, y);
          },
          false
        );
      });